import subprocess
import os
import json
import pickle
from typing import Union
from functools import reduce
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq
from collections import defaultdict
import portion as P
from prot_sql_utils import (
    query_uids_for_given_f_id,
    query_genes,
    query_ecod_subdomain_domain_counts
)
from pathlib import Path


def read_pkl_file(
        file_path: str,
) -> dict:
    with open(file_path, 'rb') as handle:
        read_file = pickle.load(handle)
    return read_file


def dump_sequence_dictionary_into_fasta_file(
        out_file_path: Path,
        sequence_dictionary: dict
) -> None:
    with open(out_file_path, "w") as handle:
        for annotation_id, annotation_sequence in sequence_dictionary.items():
            record = SeqRecord(
                Seq(annotation_sequence),
                id=str(annotation_id),
                description=''
            )
            SeqIO.write(record, handle, "fasta")


def run_hmmsearch(
        out_hmmsearch_path: str,
        hmmsearch_profile_path: str,
        fasta_file_path: str,
        evalue: float
) -> None:
    hmmsearch_command = [
        'hmmsearch',
        '--domtblout', out_hmmsearch_path,
        '-E', str(evalue),
        hmmsearch_profile_path,
        fasta_file_path
    ]
    subprocess.run(
        hmmsearch_command,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT
    )


def collect_hmm_matches(
        hmmsearch_file_path
):
    """
    parse_hmmr_output_file parses the output file of hmmsearch and returns
    a list of tuples.
    :param hmmsearch_file_path:
    :return:
    """
    # In a dombtblout output file generated by HMMER, each line represents a significant hit to a profile
    # Hidden Markov Model (HMM) from a sequence database.
    # The columns in a dombtblout file contain the following information:
    #  1. target name: the name of the sequence database entry that corresponds to the hit
    #  2. target accession: the accession of the query sequence
    #  3. tlen: the length of the target sequence
    #  4. query name: the name of the query sequence
    #  5. accession: the accession of the query sequence
    #  6. qlen: the length of the query sequence
    #  7. E-value: the expectation value (E-value) of the match
    #  8. score: the score of the match
    #  9. bias: the bias of the match
    # 10. # of domains: the number of domains in the match
    # 11. of: the number of the match in the query sequence
    # 12. c-Evalue: the conditional E-value (E-value of the match given the hit is from the same model)
    # 13. i-Evalue: the independent E-value (E-value of the match given the hit is from a different model)
    # 14. score: the score of the match
    # 15. bias: the bias of the match
    # 16. from: the start position of the match in the query sequence (1 based)
    # 17. to: the end position of the match in the query sequence (1 based)
    # 18. from: the start position of the match in the target sequence (1 based)
    # 19. to: the end position of the match in the target sequence (1 based)
    # 20. from: the start position of the envelope in the query sequence (1 based)
    # 21. to: the end position of the envelope in the query sequence (1 based)
    # 22. from: the start position of the envelope in the target sequence (1 based)
    # 23. to: the end position of the envelope in the target sequence (1 based)
    # 24. acc: the accuracy of the match
    # 25. description of target sequence: the description of the target sequence
    # 26. description of query sequence: the description of the query sequence
    # 27. # of envs: the number of envelopes in the match
    # 28. # of hmm: the number of HMMs in the match

    #  3. query name: the name of the query sequence
    matches_list = []
    with open(hmmsearch_file_path, 'r') as file_handler:
        for line in file_handler:
            if line.startswith('#'):
                continue
            fields_list = line.strip().split()

            (
                t_len,
                query_name,
                query_accession,
                qlen,
                seq_evalue,
                seq_score,
                seq_bias,
                domain_num,
                domain_total,
                domain_c_evalue,
                domain_i_evalue,
                domain_score,
                domain_bias,
                hmm_from,
                hmm_to,
                ali_from,
                ali_to,
                env_from,
                env_to,
                acc,
                target_description
            ) = fields_list[2:]
            # HMMER coordinates are 1-based and inclusive
            # we need to subtract 1 from the start position
            # to get the 0-based start position
            # Target: e.g., cds/mrna
            ali_from, ali_to = int(ali_from) - 1, int(ali_to)
            # Query: hmm profile, e.g., F group
            hmm_from, hmm_to = int(hmm_from) - 1, int(hmm_to)
            matches_list.append(
                [
                    #  the target_name is of the form gene_id-transcript_id-cds_id/gene_id-transcript_id-
                    *list([field for field in fields_list[0].rsplit('-')]),
                    t_len,
                    query_name,
                    query_accession,
                    qlen,
                    seq_evalue,
                    seq_score,
                    seq_bias,
                    domain_num,
                    domain_total,
                    domain_c_evalue,
                    domain_i_evalue,
                    domain_score,
                    domain_bias,
                    hmm_from,
                    hmm_to,
                    ali_from,
                    ali_to,
                    env_from,
                    env_to,
                    acc,
                    target_description,
                    round((hmm_to - hmm_from) / int(qlen), 3),
                    round((ali_to - ali_from) / int(t_len), 3)
                ]
            )
    return matches_list


def fetch_and_dump_data(
        file_path: Path,
        query_function: callable,
        key_format: str,
        protein_db_path: Path,
        timeout_db: int
) -> None:
    if not os.path.exists(protein_db_path):
        raise FileNotFoundError(
            f'Protein database not found: {protein_db_path},'
            f' use prot_sql_utils.py to generate it'
        )
    if not os.path.exists(file_path):
        results = query_function(
            protein_db_path,
            timeout_db
        )
        sequence_dictionary = {
            key_format.format(*sequence): (
                sequence[-1][:-1]
                if sequence[-1][-1] == '*'  # remove stop codon
                else sequence[-1]
            )
            for sequence in results if sequence[-1]
            # remove stop codon
        }
        dump_sequence_dictionary_into_fasta_file(
            out_file_path=file_path,
            sequence_dictionary=sequence_dictionary
        )


def get_hmm_matches_dictionary(
        records_with_full_domain_exon_hmm: list,
        gene_id_index: int = 1
) -> dict:
    hmm_matches_dictionary = defaultdict(list)
    for match in records_with_full_domain_exon_hmm:
        hmm_matches_dictionary[match[gene_id_index]].append(match)
    return hmm_matches_dictionary


def get_contingency_tables(
        ecod_db_path: Path,
        exonize_results_db_path: Path
) -> (list, list):
    human_genes = query_genes(db_path=exonize_results_db_path)
    (genes_with_exon_duplication_exonize,
     full_domain_exon_duplication_mrna_cds_search,
     genes_with_sub_domain_exonize,
     genes_with_full_domain_mrna_hmm,
     genes_with_full_domain_cds_hmm,
     genes_with_sub_domain_hmm,
     genes_within_domain_boundary_hmm
     ) = query_ecod_subdomain_domain_counts(
        db_path=ecod_db_path,
        hmm_mrna_table_name="x_group_filtered_ECOD_hmm_mRNA",
        hmm_cds_table_name="x_group_filtered_ECOD_hmm_CDSs",
        expansions_table_name="Expansions_full"
    )
    # Because of the overlapping threshold criteria there are some envents that can map to the same
    # match in thr Hmm search, as both, subdomain and full domain. We exclude those events since
    # they are already classified as full-domain, and this could indicate that the alignment
    # was close to our cut-off threshold.
    mrna_match_mapping_to_sub_doman_domain = [gene for gene in genes_with_sub_domain_exonize
                                              if gene not in genes_with_sub_domain_hmm]
    if mrna_match_mapping_to_sub_doman_domain:
        genes_with_sub_domain_exonize = set([gene for gene in genes_with_sub_domain_exonize
                                             if gene not in mrna_match_mapping_to_sub_doman_domain])
    # # Calculate counts
    # Genes with full domain found by HMM in mRNA and CDS
    genes_with_full_domain_hmm = genes_with_full_domain_mrna_hmm.union(genes_with_full_domain_cds_hmm)
    n_genes_with_full_domain_exon = len(genes_with_full_domain_hmm)
    # Genes with full domain exon and exon duplication (both traits)
    gene_ids_with_both_traits = genes_with_full_domain_hmm.intersection(genes_with_exon_duplication_exonize)
    n_genes_with_both_traits_fd = len(gene_ids_with_both_traits)
    # Difference to find genes with exon duplication but no full domain exon
    genes_with_exon_duplication_only_fd = genes_with_exon_duplication_exonize.difference(genes_with_full_domain_hmm)
    n_genes_with_exon_duplication_only_fd = len(genes_with_exon_duplication_only_fd)
    # Count of genes without full domain exon
    n_genes_with_no_full_domain_exon = len(human_genes) - n_genes_with_full_domain_exon
    # Odds ratio calculation: odds of a gene having an exon duplication given it has a full domain exon
    # Contingency table A: FULL-DOMAIN EXON
    contingency_table_A = [
        [n_genes_with_both_traits_fd, n_genes_with_full_domain_exon - n_genes_with_both_traits_fd],
        [n_genes_with_exon_duplication_only_fd, n_genes_with_no_full_domain_exon - n_genes_with_exon_duplication_only_fd]
    ]
    n_genes_with_both_traits_sd = len(genes_with_sub_domain_exonize.intersection(genes_with_sub_domain_hmm))
    n_genes_with_sub_domain_exon = len(genes_with_sub_domain_hmm)
    n_genes_with_exon_duplication_only_sd = len(genes_with_exon_duplication_exonize.difference(genes_with_sub_domain_hmm))
    n_genes_with_no_sub_domain_exon = len(human_genes) - n_genes_with_sub_domain_exon
    # Contingency table B: SUB-DOMAIN EXON
    contingency_table_B = [
        [n_genes_with_both_traits_sd, n_genes_with_sub_domain_exon - n_genes_with_both_traits_sd],
        [n_genes_with_exon_duplication_only_sd, n_genes_with_no_sub_domain_exon - n_genes_with_exon_duplication_only_sd]
    ]
    # Odds C:
    odds_counts_C = [
        len(full_domain_exon_duplication_mrna_cds_search),
        len(gene_ids_with_both_traits) - len(full_domain_exon_duplication_mrna_cds_search)
    ]
    return contingency_table_A, contingency_table_B, odds_counts_C


def get_overlapping_clusters(
        target_coordinates_set: set,
        threshold: float,
) -> list[list[tuple[P.Interval, Union[float, tuple]]]]:
    """
    Get overlapping clusters of target coordinates.
    """
    processed_intervals = set()
    overlapping_clusters = []
    # Sort the coordinates by their lower bound for efficient processing
    sorted_coordinates = sorted(target_coordinates_set, key=lambda x: x[0].lower)
    for target_coordinate, evalue in sorted_coordinates:
        if target_coordinate not in processed_intervals:
            # Create a cluster for the current coordinate
            cluster = [(target_coordinate, evalue)]
            # Find overlapping coordinates and add to the cluster
            for other_coordinate, other_evalue in sorted_coordinates:
                if (
                        target_coordinate != other_coordinate and
                        (min_perc_overlap(
                            intv_i=target_coordinate,
                            intv_j=other_coordinate,
                        ) >= threshold or target_coordinate.contains(other_coordinate))
                ):
                    cluster.append((other_coordinate, other_evalue))
                    processed_intervals.add(other_coordinate)
            overlapping_clusters.append(cluster)
            processed_intervals.add(target_coordinate)
    overlapping_clusters.sort(key=len, reverse=True)
    return overlapping_clusters


def get_candidate_cds(
        cds_records_dictionary: dict,
        cds_overlapping_cluster: list
):
    cdss_matches_counts = [(cds_coordinate,
                            sum([len(matches_list) for x_group_id, matches_list in cds_records_dictionary.items()]))
                           for cds_coordinate in cds_overlapping_cluster]
    candidate_cds_coordinate, _ = max(cdss_matches_counts, key=lambda x: x[1])
    return candidate_cds_coordinate


def filter_cds_records_for_gene(
        cds_records_dictionary: dict,
        threshold: float,
) -> list:
    filtered_records = []
    coordinates_set = set([(cds_coordinate, None) for cds_coordinate in cds_records_dictionary.keys()])
    overlapping_clusters_list = get_overlapping_clusters(
        target_coordinates_set=coordinates_set,
        threshold=threshold
    )
    for cds_overlapping_cluster in overlapping_clusters_list:
        if len(cds_overlapping_cluster) > 1:
            cds_keeper = get_candidate_cds(
                cds_records_dictionary=cds_records_dictionary,
                cds_overlapping_cluster=cds_overlapping_cluster
            )
        else:
            cds_keeper, _ = cds_overlapping_cluster[0]
        for x_group_name, matches_list in cds_records_dictionary[cds_keeper].items():
            if len(matches_list) > 1:
                filtered_matches = filter_matches_for_x_group(
                    matches_list=matches_list,
                    threshold=threshold
                )
                filtered_records.extend(filtered_matches)
            else:
                filtered_records.extend(matches_list)
    return filtered_records


def get_filtered_ecod_hmm_cds_records(
        hmm_hits_dictionary: dict,
        threshold: float
) -> list:
    filtered_records_list = set()
    for gene_id, cds_records_dictionary in hmm_hits_dictionary.items():
        filtered_records = filter_cds_records_for_gene(
            cds_records_dictionary=cds_records_dictionary,
            threshold=threshold
        )
        filtered_records_list.update(filtered_records)
    return list(filtered_records_list)


def filter_matches_for_x_group(
        matches_list: list,
        threshold: float,
) -> list:
    x_group_matches_list = set([
        (P.open(align_start, align_end), (annot_id, evalue))
        for annot_id, *_, align_start, align_end, evalue, _, _ in matches_list
    ])
    overlapping_clusters = get_overlapping_clusters(
        target_coordinates_set=x_group_matches_list,
        threshold=threshold
    )
    filtered_matches = []
    for cluster in overlapping_clusters:
        if len(cluster) > 1:
            min_evalue_match = min(cluster, key=lambda x: x[1][-1])
            annot_id = min_evalue_match[1][0]
        else:
            _, (annot_id, _) = cluster[0]
        filtered_matches.extend([match for match in matches_list if match[0] == annot_id])
    return filtered_matches


def intervals_percentage_overlap(
        intv_i: P.Interval,
        intv_j: P.Interval,
        ) -> float:
    if intv_i.overlaps(intv_j):
        intersection_span = get_interval_length(intv_i.intersection(intv_j))
        return round(intersection_span / get_interval_length(intv_j), 3)
    return 0.0


def create_dictionary_mrna_events(
        records_list: list,
):
    genes_dict = defaultdict(list)
    for gene_record in records_list:
        (hmm_mRNA_id,
         gene_id,
         query_name,
         x_group_name,
         x_group_id,
         ali_from,
         ali_to,
         symmetry_score,
         mapping_to_gene_intervals
         ) = gene_record
        genes_dict[gene_id].append([
            hmm_mRNA_id,
            query_name,
            x_group_name,
            x_group_id,
            symmetry_score,
            P.open(ali_from, ali_to),
            get_p_coordinates_list_union(
                p_coordinates_list=get_coordinates_list(
                    gene_mapping_coords_str=mapping_to_gene_intervals
                ))
        ])
    return genes_dict


def min_perc_overlap(
        intv_i: P.Interval,
        intv_j: P.Interval,
) -> float:
    """
    Given two intervals, the function returns the percentage of the overlapping
    region relative to the longest interval. The percentage overlap of the shortest
    interval will always be greater or equal than that of the longest interval.
    :param intv_i:
    :param intv_j:
    :return:
    """
    if intv_i.overlaps(intv_j):
        intersection_span = get_interval_length(intv_i.intersection(intv_j))
        longest_length = max(get_interval_length(intv_i), get_interval_length(intv_j))
        return round(intersection_span / longest_length, 3)
    return 0.0


def parse_txt_file(
        txt_file_path: Path,
) -> list:
    records = []
    with open(txt_file_path, 'r') as file:
        for line in file:
            # Skip commented lines
            if line.startswith('#'):
                continue
            records.append(line.strip().split('\t'))
    return records


def verify_f_group_matches_are_non_overlapping(
    hmm_mrna_matches_dict: dict,
    overlapping_threshold: float
) -> bool:
    overlapping_matches_for_f_group = False
    for gene_id, transcript_dictionary in hmm_mrna_matches_dict.items():
        for transcript_id, f_group_dictionary in transcript_dictionary.items():
            for f_group, matches_list in f_group_dictionary.items():
                if len(matches_list) > 1:
                    overlapping_list = [
                        [intv_i, intv_j]
                        for _, intv_i in matches_list
                        for _, intv_j in matches_list
                        if intv_i != intv_j and
                        intv_i.overlaps(intv_j) and
                        min_perc_overlap(intv_i, intv_j) >= overlapping_threshold
                    ]
                    if overlapping_list:
                        overlapping_matches_for_f_group = True
    return overlapping_matches_for_f_group


def get_interval_length(
        interval: P.Interval,
):
    return sum(intv.upper - intv.lower for intv in interval)


def get_coordinates_list(
        gene_mapping_coords_str: str,
) -> list[P.Interval]:
    coords_list = [
        P.open(int(start), int(end))
        for start, end in (
            pair.strip('()').split(',')
            for pair in gene_mapping_coords_str.split('_')
        )
    ]
    return sorted(coords_list, key=lambda x: (x.lower, x.upper))


def get_p_coordinates_list_union(
    p_coordinates_list: list[P.Interval],
) -> P.Interval:
    return reduce(lambda x, y: x.union(y), p_coordinates_list)


def parse_symmetry_score_x_groups_json_file_temp(
    json_file_path: Path,
    ecod_db_path: Path,
) -> list:
    symmetry_score_tuples_list = []
    with open(json_file_path, 'r') as json_file:
        x_groups_symmetry_score_dict = json.load(json_file)
    for f_id, symm_measure in x_groups_symmetry_score_dict.items():
        uids_to_update = query_uids_for_given_f_id(
            db_path=ecod_db_path,
            f_id=int(f_id)
        )
        symmetry_score_tuples_list.extend(
            [(symm_measure, uid) for uid in uids_to_update]
        )
    return symmetry_score_tuples_list


def get_representative_matches_mrna_id_set(
        matches_gene_mapping_ranges_list: list,
        overlapping_threshold: float,
):
    hmm_gene_f_group_dict = defaultdict(lambda: defaultdict(list))
    for record in matches_gene_mapping_ranges_list:
        (hmm_match_id,
         gene_id,
         f_group,
         x_group_name,
         x_group_id,
         hmm_start,
         hmm_end,
         align_start,
         align_end,
         evalue,
         symmetry_score,
         gene_mapping_coords
         ) = record
        hmm_gene_f_group_dict[gene_id][x_group_id].append((
            record,
            hmm_match_id,
            P.open(hmm_start, hmm_end),
            P.open(align_start, align_end),
            evalue,
            get_p_coordinates_list_union(
                p_coordinates_list=get_coordinates_list(
                    gene_mapping_coords_str=gene_mapping_coords
                ))
        )
        )
    representative_matches_id_list = set()
    tuples_to_insert = []
    for gene_id, f_group_dictionary in hmm_gene_f_group_dict.items():
        for x_group_id, annotation_list in f_group_dictionary.items():
            if len(annotation_list) > 1:
                overlapping_clusters = get_overlapping_clusters(
                    target_coordinates_set=set([
                        (prot_gene_coordinate, (annotation_id, evalue))
                        for _, annotation_id, _, _, evalue, prot_gene_coordinate in annotation_list]),
                    threshold=overlapping_threshold
                )
                representative_matches_id_list.update([
                    min(annotation, key=lambda x: x[-1][1])[-1][0] for annotation in overlapping_clusters
                ])
                tuples_to_insert.extend([record
                                         for record, match_id, *_ in annotation_list
                                         if match_id in representative_matches_id_list
                                         ])
            else:
                tuples_to_insert.append(annotation_list[0][0])
    return tuples_to_insert


def get_candidate_cds_coordinates(
        gene_id: str,
        gene_hierarchy_dictionary: dict,
        min_exon_length: int,
) -> dict:
    """
    get_candidate_cds_coordinates is a function that given a gene_id,
    collects all the CDS coordinates with a length greater than the
    minimum exon length across all transcript.
    If there are overlapping CDS coordinates, they are resolved
    according to the following criteria:

    * If they overlap by more than the overlapping threshold
      of both CDS lengths the one with the highest overlapping
      percentage is selected.
    * Both CDSs are selected otherwise

    The rationale behind choosing the interval with the higher percentage
    of overlap is that it will favor the selection of shorter intervals
    reducing the exclusion of short duplications due to coverage thresholds.

    :param gene_id: gene identifier
    :param gene_hierarchy_dictionary: gene hierarchy dictionary
    :param min_exon_length: minimum exon length
    :return: list of representative CDS coordinates across all transcripts
    """
    # collect all CDS coordinates and frames across all transcripts
    # we are interested in the frames to account for the unlikely event
    # that two CDS with same coordinates in different transcripts
    # have different frames
    cds_coordinates_and_frames: list[tuple[P.Interval, str]] = list(
        set(
            (coordinate, annotation_structure['frame'])
            for mrna_annotation in gene_hierarchy_dictionary[gene_id]['mRNAs'].values()
            for annotation_structure in mrna_annotation['structure']
            for coordinate in (annotation_structure['coordinate'],)
            if (
                    annotation_structure['type'] == 'CDS'
                    and (coordinate.upper - coordinate.lower) >= min_exon_length
            )
        )
    )
    if cds_coordinates_and_frames:
        representative_cds_frame_dictionary = dict()
        for cds_coordinate, frame in cds_coordinates_and_frames:
            if cds_coordinate in representative_cds_frame_dictionary:
                representative_cds_frame_dictionary[cds_coordinate] += f'_{str(frame)}'
            else:
                representative_cds_frame_dictionary[cds_coordinate] = str(frame)
        sorted_cds_coordinates_list: list[P.Interval] = sorted(
            [coordinate for coordinate, _ in cds_coordinates_and_frames],
            key=lambda coordinate: (coordinate.lower, coordinate.upper),
        )
        return dict(
            candidates_cds_coordinates=resolve_overlaps_between_coordinates(
                sorted_cds_coordinates=sorted_cds_coordinates_list
            ),
            cds_frame_dict=representative_cds_frame_dictionary,
        )
    return dict()


def resolve_overlaps_between_coordinates(
        sorted_cds_coordinates: list[P.Interval],
        overlapping_threshold: float = 0.9,
) -> list[P.Interval]:
    """
    resolve_overlaps_between_coordinates is a recursive function that given
    a list of coordinates, resolves overlaps between them.
    :param sorted_cds_coordinates: list of unique and sorted coordinates.
    :param overlapping_threshold: percentage of overlap
    :return: list of coordinates without "overlaps"
    """
    new_list = list()
    # We only process the first pair of overlapping intervals since
    # the resolved overlap could also overlap with the next interval in the list.
    intv_i, intv_j = get_first_overlapping_intervals(
        sorted_intervals=sorted_cds_coordinates,
        overlapping_threshold=overlapping_threshold
    )
    if all((intv_i, intv_j)):
        candidate = get_single_candidate_cds_coordinate(
            intv_i=intv_i,
            intv_j=intv_j
        )
        # Note: new_list is populated through enumeration
        # of 'sorted_cds_coordinates', so it will also be sorted
        # according to the same criteria used for 'sorted_cds_coordinates'.
        for idx, cds_coordinate in enumerate(sorted_cds_coordinates):
            if cds_coordinate != intv_i:
                new_list.append(cds_coordinate)
            else:
                new_list.append(candidate)
                new_list.extend(sorted_cds_coordinates[idx + 2:])
                return resolve_overlaps_between_coordinates(
                    sorted_cds_coordinates=new_list
                )
    return sorted_cds_coordinates


def get_first_overlapping_intervals(
        sorted_intervals: list[P.Interval],
        overlapping_threshold: float,
) -> Union[tuple[P.Interval, P.Interval], tuple[None, None]]:
    """
    Given a list of intervals, get_first_overlapping_intervals returns
    the first consecutive interval tuples with overlapping pairs.
    :param sorted_intervals: list of intervals
    :param overlapping_threshold: percentage of overlap
    :return: overlapping intervals pair
    """
    first_overlap_index = 0
    while first_overlap_index < len(sorted_intervals) - 1:
        current_interval = sorted_intervals[first_overlap_index]
        next_interval = sorted_intervals[first_overlap_index + 1]
        if min_perc_overlap(
                intv_i=current_interval,
                intv_j=next_interval) >= overlapping_threshold:
            return current_interval, next_interval
        first_overlap_index += 1
    return None, None


def get_single_candidate_cds_coordinate(
        intv_i: P.Interval,
        intv_j: P.Interval,
) -> P.Interval:
    """
    Given two sorted intervals this function returns the interval with
    the largerst percentage of overlap.
    Assumption: intv_i =/= intv_j and they are sorted such that
    intv_i.lower < intv_j.lower.
    param intv_i: the first interval
    param intv_j: the second interval
    Returns: P.interval
    """
    if (
            get_overlap_percentage(
                intv_i=intv_i,
                intv_j=intv_j
            ) >
            get_overlap_percentage(
                intv_i=intv_j,
                intv_j=intv_i
            )
    ):
        return intv_j
    return intv_i


def get_overlap_percentage(
        intv_i: P.Interval,
        intv_j: P.Interval,
) -> float:
    """
    Given two intervals, the function get_overlap_percentage returns the percentage
    of the overlapping region relative to an interval j.
    """
    intersection = intv_i & intv_j
    if intersection:
        return (intersection.upper - intersection.lower) / (intv_j.upper - intv_j.lower)
    return 0.0


def get_domain_matches(
    coordinates_list,
    coordinate_i,
    threshold
):
    return [
        (match_id, type_match, coordinate, coordinate_i)
        for match_id, type_match, coordinate in coordinates_list
        if min_perc_overlap(coordinate_i, coordinate) >= threshold
    ]


def get_sub_domain_matches(
    coordinates_list,
    coordinate_i,
    threshold
):
    return [
        coordinate
        for coordinate in coordinates_list
        if intervals_percentage_overlap(coordinate_i, coordinate) >= threshold
    ]


def get_mrna_matches_domain_subdomain_categories(
        query_mrna_hmm_matches_dictionary: dict,
        genes_dictionary: dict,
        exonize_events_dictionary: dict,
        gene_hierarchy_dictionary: dict,
        overlapping_threshold: float = 0.9,
        symmetry_score_threshold: float = 0.8,
):
    # FOR UPDATING THE x_group_filtered_ECOD_hmm_mRNA TABLE
    group_missing_symmetry_set = set()
    tuples_to_insert = list()
    for gene_id, mrna_hmm_matches in query_mrna_hmm_matches_dictionary.items():
        ensembl_gene_idef = f"gene:{gene_id}"
        coords, chromosome, strand = genes_dictionary[ensembl_gene_idef]
        cds_coordinates_list = get_candidate_cds_coordinates(
            gene_id=ensembl_gene_idef,
            gene_hierarchy_dictionary=gene_hierarchy_dictionary,
            min_exon_length=0
        )
        cds_coordinates_list = set([
            P.open(cds_coordinate.lower - coords.lower, cds_coordinate.upper - coords.lower)
            for cds_coordinate in cds_coordinates_list['candidates_cds_coordinates']
        ])
        gene_events_coordinates = set([
            coordinate
            for events_list in exonize_events_dictionary[gene_id].values()
            for coordinate, *_, in events_list
        ])
        cds_coordinates_list = cds_coordinates_list.union(gene_events_coordinates)
        for full_domain_match in mrna_hmm_matches:
            mrna_match_id, *_, x_group_id, symmetry_score, _, gene_mapping_coord = full_domain_match
            is_within_domain_boundary, is_full_domain_exon, is_subdomain_exon = 0, 0, 0
            cds_domain_matches = [
                coordinate
                for coordinate in cds_coordinates_list
                if min_perc_overlap(gene_mapping_coord, coordinate) >= overlapping_threshold
            ]
            if cds_domain_matches:
                is_full_domain_exon += len(set(cds_domain_matches))
            else:
                cds_sub_domain_matches = get_sub_domain_matches(
                    coordinates_list=cds_coordinates_list,
                    coordinate_i=gene_mapping_coord,
                    threshold=overlapping_threshold
                )
                if cds_sub_domain_matches:
                    n_cdss_matching = len(set(cds_sub_domain_matches))
                    is_within_domain_boundary += n_cdss_matching
                    if symmetry_score is not None and symmetry_score >= symmetry_score_threshold:
                        if symmetry_score >= symmetry_score_threshold:
                            is_within_domain_boundary -= n_cdss_matching
                            is_subdomain_exon += n_cdss_matching
                    else:
                        group_missing_symmetry_set.add(x_group_id)
            tuples_to_insert.append((
                is_within_domain_boundary,
                is_full_domain_exon,
                is_subdomain_exon,
                mrna_match_id
            ))
    return tuples_to_insert, group_missing_symmetry_set


def get_events_domain_subdomain_categories(
    exonize_events_dictionary: dict,
    hmm_mrna_cds_matches_dict: dict,
    gene_hierarchy_dictionary: dict,
    overlapping_threshold: float = 0.9,
    symmetry_score_threshold: float = 0.2,
):
    # FOR UPDATING THE Events TABLE
    x_group_ids_missing_symmetry_score_set = set()
    records_to_insert_matches_events = list()
    records_to_insert = list()
    for gene_id, expansion_dictionary in exonize_events_dictionary.items():
        trimmed_gene_id = gene_id.rsplit(':')[1]
        gene_start = gene_hierarchy_dictionary[gene_id]['coordinate'].lower
        if trimmed_gene_id in hmm_mrna_cds_matches_dict:
            mrna_hmm_matches = hmm_mrna_cds_matches_dict[trimmed_gene_id]
            for expansion_id, events_list in expansion_dictionary.items():
                for event in events_list:
                    event_coordinate, event_type = event
                    is_within_domain_boundary, is_full_domain_exon, is_subdomain_exon = 0, 0, 0
                    full_domain_matches_coordinates = get_domain_matches(
                        coordinates_list=[
                            (match_id, match_type, gene_mapping_coord)
                            for xid, coordinates_list in mrna_hmm_matches.items()
                            for match_type, match_id, gene_mapping_coord, _ in coordinates_list
                        ],
                        coordinate_i=event_coordinate,
                        threshold=overlapping_threshold
                    )
                    if full_domain_matches_coordinates:
                        is_full_domain_exon = len(full_domain_matches_coordinates)
                        records_to_insert_matches_events.extend([
                            (type_match,
                             'FullDomainExon',
                             match_id,
                             gene_id,
                             event_coords.lower,
                             event_coords.upper)
                            for (match_id,
                                 type_match,
                                 match_coords,
                                 event_coords) in full_domain_matches_coordinates
                        ])
                    else:
                        subdomain_matches = [
                            (x_group_id,
                             match_id,
                             match_type,
                             gene_mapping_coord,
                             event_coordinate,
                             symmetry_score)
                            for x_group_id, coordinates_list in mrna_hmm_matches.items()
                            for match_type, match_id, gene_mapping_coord, symmetry_score in coordinates_list
                            if intervals_percentage_overlap(
                                gene_mapping_coord, event_coordinate
                            ) >= overlapping_threshold
                        ]
                        if subdomain_matches:
                            for (x_group_id,
                                 match_id,
                                 match_type,
                                 gene_mapping_coord,
                                 event_coordinate,
                                 symmetry_score) in subdomain_matches:
                                is_within_domain_boundary += 1
                                if symmetry_score:
                                    if symmetry_score >= symmetry_score_threshold:
                                        records_to_insert_matches_events.append((
                                            match_type,
                                            'SubDomainExon',
                                            match_id,
                                            trimmed_gene_id,
                                            event_coordinate.lower,
                                            event_coordinate.upper
                                        ))
                                        is_subdomain_exon += 1
                                        is_within_domain_boundary -= 1
                                    else:
                                        records_to_insert_matches_events.append((
                                            match_type,
                                            'WithinDomainBoundary',
                                            match_id,
                                            trimmed_gene_id,
                                            event_coordinate.lower,
                                            event_coordinate.upper
                                        ))
                                else:
                                    x_group_ids_missing_symmetry_score_set.add(x_group_id)
                    records_to_insert.append((
                        is_within_domain_boundary,
                        is_full_domain_exon,
                        is_subdomain_exon,
                        gene_id,
                        event_coordinate.lower + gene_start,
                        event_coordinate.upper + gene_start
                    ))
        else:
            for expansion_id, events_list in expansion_dictionary.items():
                for event in events_list:
                    event_coordinate, event_type = event
                    records_to_insert.append((
                        0,
                        0,
                        0,
                        gene_id,
                        event_coordinate.lower + gene_start,
                        event_coordinate.upper + gene_start
                    ))
    return records_to_insert, records_to_insert_matches_events, x_group_ids_missing_symmetry_score_set
